### ISSUE TITLE
cat: 'libtensorflow*.so_?': No such file or directory

### ISSUE THREAD

**Issue by zongoalbert** [JdeRobot/smart-traffic-sensor#10]
i did not found this directory in your code : src/lib/ then i have added directory lib with command line `cd src` then `mkdir lib`  : 
when i run this command line `pushd . && cd src/lib/ && cat libtensorflow*.so_? > libtensorflow_cc.so && popd` it give me this error :  

> cat: 'libtensorflow*.so_?': No such file or directory

**Comment by rkachach** [comment]
Instructions on the Readme were not correct. Now it reflects the correct procedure for a successful building.
